### PR TITLE
Api configuration

### PR DESCRIPTION
**Pull request by althafaz**
made some changes on home page, and recipe search page.
url: http://localhost:5173/account/meal-prep

### CODE REVIEW

**Review by tim-eich — DISMISSED** [review]
Looks good! Sorry for the hold up, I thought the search feature you were showing us was part of this, and might need a little testing.

**Review by Johngh1212 — DISMISSED** [review]

**Review by Avecilla19 — DISMISSED** [review]

**Review by Johngh1212 — DISMISSED** [review]
Looks good

**Review by tim-eich — APPROVED** [review]
Still looks good, I pushed the package-lock stuff straight to this branch, so you should be alright to merge

**Review by Johngh1212 — APPROVED** [review]
Looks good.com

**Pull request merged**
